import type { LucideIcon } from 'lucide-react';
import {
  Anchor,
  Baby,
  BadgeCheck,
  Banknote,
  Bolt,
  BookOpen,
  BookUser,
  BriefcaseBusiness,
  Building2,
  Bus,
  Cable,
  Calculator,
  Car,
  ClipboardCheck,
  ClipboardList,
  CloudRain,
  CloudSun,
  Cpu,
  Droplets,
  Factory,
  FileBadge,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  Flame,
  Gavel,
  Globe,
  GraduationCap,
  HandHeart,
  HeartHandshake,
  HeartPulse,
  Home,
  IdCard,
  Landmark,
  LayoutGrid,
  Library,
  Lightbulb,
  Mail,
  Map,
  Microscope,
  Monitor,
  Mosque,
  Network,
  Package,
  Phone,
  Pill,
  Plane,
  Radio,
  Receipt,
  Scale,
  School,
  ScrollText,
  SearchX,
  Shield,
  ShieldAlert,
  Ship,
  ShipWheel,
  Sprout,
  Stamp,
  Stethoscope,
  Store,
  TrainFront,
  University,
  Users,
  UserRound,
  Utensils,
  Wallet,
  Zap,
} from 'lucide-react';

/** Lucide keys used by Category YAML and optional Service `icon` fields. */
const BY_KEY: Record<string, LucideIcon> = {
  landmark: Landmark,
  fingerprint: Fingerprint,
  banknote: Banknote,
  car: Car,
  map: Map,
  'graduation-cap': GraduationCap,
  'heart-pulse': HeartPulse,
  shield: Shield,
  zap: Zap,
  plane: Plane,
  scale: Scale,
  'id-card': IdCard,
  'book-user': BookUser,
  receipt: Receipt,
  'file-text': FileText,
  'scroll-text': ScrollText,
  globe: Globe,
  radio: Radio,
  droplets: Droplets,
  'train-front': TrainFront,
  'file-badge': FileBadge,
  flame: Flame,
  wallet: Wallet,
  stamp: Stamp,
  lightbulb: Lightbulb,
  mail: Mail,
  cpu: Cpu,
  network: Network,
  'briefcase-business': BriefcaseBusiness,
  'cloud-sun': CloudSun,
  factory: Factory,
  sprout: Sprout,
  monitor: Monitor,
  'hand-heart': HandHeart,
  store: Store,
  'clipboard-list': ClipboardList,
  'heart-handshake': HeartHandshake,
  'building-2': Building2,
  'file-spreadsheet': FileSpreadsheet,
  'book-open': BookOpen,
  university: University,
  school: School,
  library: Library,
  'badge-check': BadgeCheck,
  'clipboard-check': ClipboardCheck,
  baby: Baby,
  utensils: Utensils,
  pill: Pill,
  stethoscope: Stethoscope,
  microscope: Microscope,
  'user-round': UserRound,
  gavel: Gavel,
  home: Home,
  users: Users,
  mosque: Mosque,
  'ship-wheel': ShipWheel,
  anchor: Anchor,
  'cloud-rain': CloudRain,
  'shield-alert': ShieldAlert,
  package: Package,
  calculator: Calculator,
  ship: Ship,
  bus: Bus,
  phone: Phone,
  bolt: Bolt,
  cable: Cable,
};

export function lucideIconFor(key: string | undefined | null): LucideIcon {
  if (!key) return Landmark;
  return BY_KEY[key] ?? Landmark;
}

export { LayoutGrid, SearchX };
